version: "3.9"
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.production
    image: ikintosh/devops-for-programmers-project-lvl1
    command: npm test
    depends_on:
      db:
        condition: service_healthy
  db: 
    image: postgres:14.3
    environment:
      POSTGRES_USER: "${DATABASE_USERNAME}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_DB: "${DATABASE_NAME}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
