version: "3.3"
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.production
    image: ikintosh/devops-for-programmers-project-lvl1
    command: bash -c 'sleep 3 && npm test'
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
  db: 
    image: postgres:14.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
