version: "3.9"
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.production
    image: ikintosh/devops-for-programmers-project-lvl1
    command: npm test
    depends_on:
      db:
        condition: service_healthy
  db: 
    image: postgres:14.3
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "postgres"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
