services:
  app:
    build: .
    volumes:
      - ./app:/app
    ports: 
    - 8080:8080
    command: npm run dev
  caddy:
    image: caddy:2.5.1
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app